[project]
name = "ai-web-explorer"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Milos Svana", email = "milos.svana@gmail.com" }
]
dependencies = [
    "playwright>=1.42.0",
    "openai>=1.14.2",
    "python-dotenv>=1.0.0",
]
readme = "README.md"
requires-python = ">= 3.9"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
web-kobe = "ai_web_explorer.safesym_bridge.cli:main"

[tool.rye]
managed = true
dev-dependencies = [
    "black>=24.3.0",
    "pytest>=8.2.2",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/ai_web_explorer"]
